### ISSUE TITLE
Wifi is not working 

### ISSUE THREAD

**Issue by jeanix67** [osx86-ijb/Dell-Latitude-e5430-3rd-Gen-Core-i5-3210m-macOS-BigSur#1]
Hi ijb, this is pretty good but the sound and wifi are missing, any advice to understand where to start the investigation?
https://www.youtube.com/watch?v=ii2ZEPJ2lzg&ab_channel=TechLabs do you think this is viable solution?

**Comment by osx86-ijb** [comment]
Whilst I know that this might not be helpful, do know that I find it odd, as both are working on my machine.
Did you double-check to make sure that it is the same Wi-Fi chipset? Regarding sound, I'd double check your config.plist, as there might be a layout-id set improperly?

**Comment by osx86-ijb** [comment]
> Hi ijb, this is pretty good but the sound and wifi are missing, any advice to understand where to start the investigation?
> https://www.youtube.com/watch?v=ii2ZEPJ2lzg&ab_channel=TechLabs do you think this is viable solution?

It also looks like based upon the YouTube link that you've pasted in your comment that you're attempting to use an Intel Wi-Fi based chipset for that machine? If so, you'll have to follow steps for that instead, as the hardware used in this build was the Broadcom BCM94352HMB Azurewave AW-CE123H.
